apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: imshubhamkaushik/task-service:latest
          ports:
            - containerPort: 10002
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/taskdb
            - name: PORT
              value: "10002"
